base_url: minimaal
site_title: minimaal
site_description: a lightweight, minimal static blog generator written in python using markdown and jinja2
directories:
  posts: posts
  template: template
  output: docs
date_format: '%d/%m/%Y'
posts_per_page: 10
css:
  - https://fonts.googleapis.com/css?family=Open+Sans:300
  - https://cdn.rawgit.com/necolas/normalize.css/master/normalize.css
  - https://cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css
  - file:///home/jamie/Desktop/workspace/projects/minimaal/template/css/minimaal.css