base_url: xyz.com
site_title: Jamie MacLeod
site_description: a random collection of thoughts on software, technology, and personal finance
posts_directory: posts
template_directory: template
output_directory: docs
date_format: '%d/%m/%Y'
posts_per_page: 10
social_links:
  facebook: https://www.facebook.com/abc123abc321
  github:   https://github.com/macleodmac
css:
  - https://fonts.googleapis.com/css?family=Open+Sans:300
  - https://cdn.rawgit.com/necolas/normalize.css/master/normalize.css
  - https://cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css
  - file:///home/jamie/Desktop/Projects/minimaal/template/css/black.css